BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rpi-detector"
BBFILE_PATTERN_rpi-detector = "^${LAYERDIR}/"
BBFILE_PRIORITY_rpi-detector = "6"

LAYERVERSION_rpi-detector = "1"
LAYERDEPENDS_rpi-detector = "core openembedded-layer meta-python networking-layer"
LAYERSERIES_COMPAT_rpi-detector = "kirkstone"
